# Generated by Django 3.1.5 on 2024-07-21 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAndOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(help_text='The Track number on the playlist')),
                ('track', models.ForeignKey(help_text='Track refers to the playlist', on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='grunge.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID')),
                ('name', models.CharField(help_text='The playlist name', max_length=100)),
                ('trackandorder', models.ForeignKey(help_text='The track and its order', on_delete=django.db.models.deletion.CASCADE, related_name='trackorder', to='grunge.trackandorder')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['name'], name='grunge_play_name_ed1809_idx'),
        ),
    ]
