# Generated by Django 3.1.5 on 2024-07-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0002_auto_20240721_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackandorder',
            options={'ordering': ('order', 'playlist', 'track')},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='trackandorder',
        ),
        migrations.AddField(
            model_name='trackandorder',
            name='playlist',
            field=models.ForeignKey(help_text='The playlist of the track', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='grunge.playlist'),
        ),
        migrations.AddIndex(
            model_name='trackandorder',
            index=models.Index(fields=['order', 'playlist', 'track'], name='grunge_trac_order_c3f511_idx'),
        ),
    ]
