# Generated by Django 3.1.5 on 2024-07-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0003_auto_20240721_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackandorder',
            options={'ordering': ('playlist', 'track', 'order')},
        ),
        migrations.AlterField(
            model_name='trackandorder',
            name='track',
            field=models.ForeignKey(help_text='Track refers to the playlist', on_delete=django.db.models.deletion.CASCADE, related_name='track', to='grunge.track'),
        ),
        migrations.AddConstraint(
            model_name='trackandorder',
            constraint=models.UniqueConstraint(fields=('playlist', 'track'), name='unique_track'),
        ),
    ]
