# Generated by Django 3.1.5 on 2024-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0004_auto_20240722_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackandorder',
            name='order',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='The Track number on the playlist', null=True),
        ),
    ]
